---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: homeassistant-apps/workflows/.github/workflows/addon-ci.yaml@607d74cf7c960ca75cda4d8efe0d1746406bb503 # main
