---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: homeassistant-apps/workflows/.github/workflows/addon-ci.yaml@3e87ab2e2f828b053c28d9eb642e0cbcfff22c90 # main
