---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  workflows:
    uses: homeassistant-apps/workflows/.github/workflows/addon-ci.yaml@28ee308a0b2bdb36a58019ad320f0e3ba37b0f72 # main
