---
name: Sync labels
permissions:
  contents: read
  pull-requests: write

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

jobs:
  workflows:
    uses: homeassistant-apps/workflows/.github/workflows/labels.yaml@f05e01b037d0b6a1bb7b057499a491a29635372d # main
