---
name: Sync labels
permissions:
  contents: read
  pull-requests: write

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

jobs:
  workflows:
    uses: homeassistant-apps/workflows/.github/workflows/labels.yaml@28ee308a0b2bdb36a58019ad320f0e3ba37b0f72 # main
