---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  workflows:
    uses: homeassistant-apps/workflows/.github/workflows/pr-labels.yaml@607d74cf7c960ca75cda4d8efe0d1746406bb503 # main
