---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  workflows:
    uses: homeassistant-apps/workflows/.github/workflows/pr-labels.yaml@3e87ab2e2f828b053c28d9eb642e0cbcfff22c90 # main
