---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  workflows:
    uses: homeassistant-apps/workflows/.github/workflows/pr-labels.yaml@32cc61a454ed049959c9b3c22b798c75c3731af8 # main
