---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  workflows:
    uses: homeassistant-apps/workflows/.github/workflows/release-drafter.yaml@ef730c699b90c59beed86039277f7cbb82928e67 # main
