---
name: Release Drafter

permissions:
  contents: write
  pull-requests: read

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  workflows:
    uses: homeassistant-apps/workflows/.github/workflows/release-drafter.yaml@28ee308a0b2bdb36a58019ad320f0e3ba37b0f72 # main
