---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  workflows:
    uses: homeassistant-apps/workflows/.github/workflows/release-drafter.yaml@65123ada0a16637a1afafa5f2173b47c84520882 # main
