---
name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  workflows:
    uses: homeassistant-apps/workflows/.github/workflows/stale.yaml@65123ada0a16637a1afafa5f2173b47c84520882 # main
