---
name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  workflows:
    uses: homeassistant-apps/workflows/.github/workflows/stale.yaml@a1077d7df8e84a9fcc06a877333ad5e303743f00 # main
